# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:gi
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
CONSUMER_KEY : '5FkuMYrnSEq07alhOr0w2Bslp'
CONSUMER_SECRET: 'W8GCayISyh7cIyShSqbWJuNi9Klcl7xFh1KvBSV37e6Be0rjAQ'
access_token: '3270151596-v6jG6jYueNJrLiNvgDlXwmJrm3e43XtOVAMoNfq'
access_secret: 'My0thVuru1GDuBSml18WMt4V2exRQacpn1fkO1bf6drxu'
instagram_token: '3244132945.1677ed0.326e0f78a5154d389235d46b0ed05f6b'
facebook_app_id: '314376906097148'
facebook_secret: '2902b5cd6325680cb2d63f91e76f3e39'
github_id: '035c5bc69d27785089e1'
github_secret: '6d4b316e73a5b369c76c5da80813653b58ede589'

google_id: '551336306859-r20vj7ra369a94atpcamecb5n4ek0jc2.apps.googleusercontent.com'
google_secret: 'wuMN7Otn5l7xM_pKD6faLKcq'